name: Create PR Preview Plugin

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip plugin to prevent double-zipping in the next step
        run: unzip create-content-model.zip -d create-content-model

      - name: Zip the contents to create plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: create-content-model
          path: create-content-model
